### PR TITLE
Update make_member to union membership lists

### PR DESCRIPTION
**Pull request by MattyTheHacker**
aboslutely no fucking clue if this will work but 🤷

### CODE REVIEW

**Comment by CarrotManMatt** [comment]
Have now fixed workflows so checks should work now.

**Comment by CarrotManMatt** [comment]
From my previous looks of the guild html I thought the `all_members` included the `standard_members` table? I'm not 100% sure because you have seen the admin page & I haven't. To be fair it ends up as a dictionary anyway so duplicate keys shouldn't be an issue.

**Comment by MattyTheHacker** [comment]
When I looked last night it was different - there was only 5 in the "All Members" table but I've just checked again now and the tables are now identical.

**Comment by CarrotManMatt** [comment]
Is it worth asking someone at the guild what the tables are supposed to represent so that we know which ones to include for certain?

**Comment by MattyTheHacker** [comment]
lmao I doubt anyone at the guild knows either.
In theory standard members table is just for normal members like students
If we get any external members another table will pop up for that
and there also used to be an option for people to click a button to say they're "interested in" the society
so the reason it was a union was I think because we needed all members excluding the interested in people cos they hadn't actually bought membership

**Comment by CarrotManMatt** [comment]
So would the "interested in" students be within the `all_members` table? If so, surely we can't use that table because then they would be accepted as a paid member? I'm just still confused towards the purpose of the union because I thought all the real members were just within the `standard_members` table. I would understand if we had to union the `standard_members` table with the `external_members` table in order to get all the real members excluding just "interested in" students

**Comment by MattyTheHacker** [comment]
hmm yeah maybe this is me being dumb - @sapphyree would know better

**Review by CarrotManMatt — APPROVED** [review]
Mmm self review. Looks good, me.

**Comment by CarrotManMatt** [comment]
Bump, to see if test workflow runs.

**Review by codemicro — APPROVED** [review]
These class names pain me

**Comment by CarrotManMatt** [comment]
> These class names pain me

The guilds HTML ones? God yes, they are disgusting

**Pull request merged**
