### PR TITLE
Add `poetry-check` test workflow

### PR DESCRIPTION
**Pull request by CarrotManMatt**

### CODE REVIEW

**Review by codemicro — APPROVED** [review]
Looks good - I'm assuming this functions fine but because it's a difficult-to-test CI thing that's only for QA I'm happy to merge it in as is without that assurance.

**Comment by codemicro** [comment]
Actually, a thought: would it be beneficial to have the `workflow_dispatch` trigger enabled on this action too for testing purposes?

**Comment by CarrotManMatt** [comment]
As in to run all the tests? Why would you need to rerun the tests if the files haven't changed? Because as soon as a file is changed the tests already auto rerun.

**Comment by codemicro** [comment]
It was before I remembered that it would fire as soon as we merged this in anyway, so ignore me. Good to merge if you are.

**Pull request merged**
