### PR TITLE
Add debug logging

### PR DESCRIPTION
**Pull request by MattyTheHacker**

### CODE REVIEW

**Comment by CarrotManMatt** [comment]
Removed linked issue so that it will not be auto-closed. (This PR will not fully solve the issue)

**Comment by MattyTheHacker** [comment]
It will when it's finished 😭 it's only a draft 💀

**Comment by CarrotManMatt** [comment]
Your title suggests it will only fix it for the /archive command tho? I wasn't looking at any submitted changes/the fact that it's a draft.

**Comment by CarrotManMatt** [comment]
Although I now see your branch name suggests otherwise

**Comment by MattyTheHacker** [comment]
yea the name is fucked, didn't realise it'd done that

**Comment by CarrotManMatt** [comment]
Oh it's pulled it from the commit message. My bad for the confusion

**Review by CarrotManMatt — CHANGES_REQUESTED** [review]
When sending a message with `self.command_send_error()` the error message is already added to the console, so duplicating it as a debug message seems redundant. Instead it would be more useful to debug log that the command ended processing, if an error occurs.

**Comment by MattyTheHacker** [comment]
> When sending a message with `self.command_send_error()` the error message is already added to the console, so duplicating it as a debug message seems redundant. Instead it would be more useful to debug log that the command ended processing, if an error occurs.

Is it worth just removing those log bits entirely? I don't mind either way

**Review by CarrotManMatt — APPROVED** [review]
It would be most helpful if every debug message also included the command name (similar to when an error is logged). To prevent duplication of code this could be refactored into a new function: `self.log_debug()` where similar formatting is used from the `self.command_send_error()` function, and the command name is logged along with the message.

In addition a boolean flag should be able to be passed as an argument, so that when no custom message is given, that flag states that the command exited because of an error: E.g. the logged messages could be `makemember | Command execution terminated with the above error`.

**Review by CarrotManMatt — CHANGES_REQUESTED** [review]
Pressed the wrong button again

**Comment by CarrotManMatt** [comment]
Perhaps a better option would be to use a unique `LoggerAdapter` at the top of every cog file, along with the format specifier including the command name, that way the command name does not need to be manually added to the context each time.

See https://docs.python.org/2/library/logging.html#loggeradapter-objects

**Comment by MattyTheHacker** [comment]
yeah nah can't be fucked doing that lmao, if that's what you want probs worth closing the PR entirely and just opening an issue

**Pull request closed without merging**
