### PR TITLE
Update build-push-action to v6

### PR DESCRIPTION
**Pull request by MattyTheHacker**

### CODE REVIEW

**Comment by MattyTheHacker** [comment]
I don't know how but the manifest issue has mysteriously fixed itself 😭

**Comment by CarrotManMatt** [comment]
> I don't know how but the manifest issue has mysteriously fixed itself 😭

U got a link to the docs where it discussed what needed to be added as the manifest file?

**Comment by MattyTheHacker** [comment]
the issues I found are linked on the issue, entirely possible I'd just fucked something up somehwo

**Comment by CarrotManMatt** [comment]
After looking at the links in the attached issues. The manifest file error was caused by temporary errors in the GitHub runners. Seems like if we had just rerun the action that failed it would have succeeded

**Comment by MattyTheHacker** [comment]
Well the action didn't fail - the action succeeded and pushed just fine, but when you tried to download the image it would fail. either way seems to be sorted now

**Review by CarrotManMatt — APPROVED** [review]

**Pull request merged**
