### PR TITLE
Convert Markdown to Asciidoc

### PR DESCRIPTION
**Pull request by CarrotManMatt**

### CODE REVIEW

**Comment by codemicro** [comment]
What's the reasoning for this? No other CSS project uses asciidoc - it also doesn't render nicely in Github.

**Comment by CarrotManMatt** [comment]
Admittedly it's personal preference and the ease for their formatting of tables, URLs & code blocks. I've never been very pleased with the rendering of the table within the README.

Could you give examples of where GitHub's poor support for Asiidoc impacts rendering? (I am aware the rendering is currently broken for this branch, but that is why this PR is currently a draft)

**Comment by codemicro** [comment]
I was unaware rendering was broken specifically for this branch - that's what I was referring to. I would still much rather not convert the project to it however as it's a comparatively unknown format.

**Comment by CarrotManMatt** [comment]
Just because the format is less well known than markdown (which i would attribute to markdown's simplicity & thus fewer formatting features) doesn't mean we should disregard AsciiDoc.

The document complexity is so similar between the two. In addition AsciiDoc has a much more comprehensive set of documentation for it's more advanced features, compared to Markdown's inherent lack of standardisation.

https://docs.asciidoctor.org

**Comment by CarrotManMatt** [comment]
There are also additional features provided by AsciiDoc that I hope to make use of to improve the quality of TeX-Bot's documentation that would not even be possible in Markdown.

* [Keyboard macros](https://docs.asciidoctor.org/asciidoc/latest/macros/keyboard-macro/)
* [Button & menu UI macros](https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros)
* [Collapsible blocks](https://docs.asciidoctor.org/asciidoc/latest/blocks/collapsible/)
* [substitutions](https://docs.asciidoctor.org/asciidoc/latest/subs/)
* [Source code callouts](https://docs.asciidoctor.org/asciidoc/latest/verbatim/callouts/)
* Source code within list elements
* Lists within table cells

**Comment by codemicro** [comment]
Even based on that message, I do not see a strong reason to convert everything to AsciiDoc, predominantly as it is established as the documentation format org-wide and there is nothing present in AsciiDoc that cannot be achieved or approximated with Markdown.

For example, keyboard macros can be `CTRL+I` inline code, as can `[ Buttons ]` and `Menu > Options` and native HTML can easily be fallen back on where features are not supported by Markdown...

<details><summary>... like in collapsible blocks ...</summary>Hello!</details>

I also believe that simplicity should be valued - this project is already decently complex and, as this is not primarily a documentation project, I see no reason to increase complexity anywhere else when what is currently in use is functional.

The lack of a central Markdown specification is not important as [Github flavoured Markdown](https://github.github.com/gfm/) is strongly defined and very widely supported by editors and other tools.

**Comment by CarrotManMatt** [comment]
Good points. I agree with the need to reduce complexity & having an org wide standard docs format. I was just unaware that Markdown had already been selected in concrete terms. Has this been documented anywhere?

I still think there is greater benefit to not having to fall back to html for more complex formatting & abstracting the rendering of components like the button & keyboard macros has the benefit of multiple rendering styles rather than only being able to render as square brackets. E.g. image

**Comment by codemicro** [comment]
There's no written standard, the justification is based on precedent as it's been used for all writing in other repos and in some places on the website.

**Pull request closed without merging**
