### PR TITLE
Downgrade role reminder to warning - temp fix

### PR DESCRIPTION
**Pull request by MattyTheHacker**

### CODE REVIEW

**Comment by MattyTheHacker** [comment]
> If it's not working correctly, it shouldn't be active.
it's not active

**Comment by FrozenDude101** [comment]
> it's not active so no issue there

it's active enough to spam the channel

**Comment by MattyTheHacker** [comment]
> > it's not active so no issue there
> 
> it's active enough to spam the channel

that's just part of start up checks - the feature itself is not enabled

**Comment by MattyTheHacker** [comment]
I agree this does need to be fixed, but this is a short term thing to prevent it spamming while we try to fix it

**Review by CarrotManMatt — APPROVED** [review]

**Pull request merged**
