### PR TITLE
Use relative import statements

### PR DESCRIPTION
**Pull request by MattyTheHacker**

### CODE REVIEW

**Review by CarrotManMatt — CHANGES_REQUESTED** [review]
IMO the utils imports that aren't with `utils/__init__.py` should be left as absolute as it improves clarity & consistency. The same import statement is used in the cogs and the utils.

**Comment by MattyTheHacker** [comment]
> IMO the utils imports that aren't with `utils/__init__.py` should be left as absolute as it improves clarity & consistency. The same import statement is used in the cogs and the utils.

So just so I understand the only file you would want changed is the utils init? and everything else just as it was? or do you want the cogs init changed as well

I can see the argument but I'd like to keep as consistent as we can one way or the other and tbf I think my preference is relative wherever we can but I dont mind too muich

**Comment by CarrotManMatt** [comment]
I would have originally said change `utils/__init__.py` *and* `cogs/__init__.py`, however I'm currently doing a bit more research into the pros/cons of relative imports. (Checkout https://youtu.be/uwtupH7LJco?si=B-LF9ditT8izLHqR for context).

The main point the video makes is that relative imports only work if you run the python script with the `-m` flag. Thankfully we currently do.

The main benefit of relative imports is to reduce unwieldy long import statements many levels deep, or to allow restructuring parent modules without affecting lower module's imports. Because we don't run into either of those issues I would rather keep the imports more clear on the location the classes/functions are coming from.

Further reading:
https://realpython.com/absolute-vs-relative-python-imports
https://stackoverflow.com/questions/4209641/absolute-vs-explicit-relative-import-of-python-module

**Comment by MattyTheHacker** [comment]
Yeah just quickly watched that video - sounds like just using absolute is the easiest / simplest, though again I don't care particularly much as long as it's consistent

**Comment by CarrotManMatt** [comment]
I think I'm gonna stand by being annoying and advocate for the inconsistent. Use relative within `__init__.py` files or relational connections (E.g. importing custom exception classes from `exceptions/base.py`), use absolute elsewhere.

**Review by CarrotManMatt — APPROVED** [review]

**Pull request merged**
