### PR TITLE
Track moderation actions

### PR DESCRIPTION
**Pull request by CarrotManMatt**
Tracks which users have had moderation actions taken against them, and increases the number of strikes associated with their account.

### CODE REVIEW

**Comment by CarrotManMatt** [comment]
TODO list:

- [x] Store number of strikes against user in database
- [ ] Env variable to enable/disable strike tracking
- [ ] Automatic strike tracking
    - [ ] Event handler to identify when moderation actions are done manually
    - [ ] Message committee member:
        - [ ] Ask if they meant to administer a strike or they were just doing a silly
            - [ ] Buttons view
        - [ ] Tell them to use the /strike command in future
    - [ ] Ensure striked user is not committee member
        - [ ] Ask striker if they would like to retract the action
            - [ ] Buttons view
    - [ ] Increment strike if less than 3
    - [ ] Validate correct moderation action according to current strike level
        - [ ] Ask striker if they would like to undo incorrect action then perform correct action
            - [ ] Buttons view
    - [ ] Send message to user detailing reason for strike, applied moderation action & where to find rules etc.
- [ ] /strike command
    - [ ] User autocomplete (same as /induct)
    - [ ] Allow command to be run as user context menu command
    - [ ] Ensure striked user is member of CSS server
    - [ ] Increase strike count if less than 3
        - [ ] Warning if count is not less than 3 and ask if final strike moderation action should be taken (AKA why are they still in the server with >= 3 strikes?)
    - [ ] Perform moderation action according to new strike value
    - [ ] Send message to user detailing reason for strike, applied moderation action & where to find rules etc.

**Review by FrozenDude101 — COMMENTED** [review]
Probably works, idk

**Comment by Thatsmusic99** [comment]
matthew that is not how you review code mate

**Comment by FrozenDude101** [comment]
still probably works, idk

**Comment by CarrotManMatt** [comment]
> * When the strike command is run and a timeout/kick/ban is issued, does it confirm in the audit log who ran it (similar to when TeX points out the user running a slash command for induction)?

A committee member is always required to confirm before any action is applied

**Comment by CarrotManMatt** [comment]
> * In the event of a strike being issued on accident (e.g. incorrect user is striked, or receives two strikes from different committee members for the same offence), can they be reversed already? I'm not sure I saw any mention of strike reversal in the PR, but that may just be me being blind

See #71

**Review by MattyTheHacker — APPROVED** [review]
looks good to me chief,

good fuckin yard

**Pull request merged**
