### PR TITLE
Improve variable names & docs & .gitignore

### PR DESCRIPTION
**Pull request by CarrotManMatt**
See commit messages for the specific changes that have been made.

**!!REQUIRES CHANGES TO DEPLOYMENT ENVIRONMENT VARIABLES!!**
The following environment variables will need to be added to all existing deployments after this PR is merged:

- `GROUP_NAME`
- `PURCHASE_MEMBERSHIP_URL`
- `MEMBERSHIP_PERKS_URL`
- `MEMBERSHIP_PRICE`
- `MEMBERS_LIST_URL` (renamed from `MEMBERS_PAGE_URL`)
- `MEMBERS_LIST_URL_SESSION_COOKIE` (renamed from `MEMBERS_PAGE_COOKIE`)
- `SEND_INTRODUCTION_REMINDERS_INTERVAL` (renamed from `INTRODUCTION_REMINDER_INTERVAL`)
- `KICK_NO_INTRODUCTION_DISCORD_MEMBERS` (renamed from `KICK_NO_INTRODUCTION_MEMBERS`)
- `KICK_NO_INTRODUCTION_DISCORD_MEMBERS_DELAY` (renamed from `KICK_NO_INTRODUCTION_MEMBERS_DELAY`)
- `SEND_GET_ROLES_REMINDERS_INTERVAL` (renamed from `GET_ROLES_REMINDERS_INTERVAL`)

### CODE REVIEW

**Review by codemicro — APPROVED** [review]
blind review time wahoo

**Comment by CarrotManMatt** [comment]
> blind review time wahoo

Admittedly this is the one that needs to be worried about least, cos most of it is docs changes. And its very difficult to introduce bugs/malicious code into docs

**Comment by codemicro** [comment]
Is `MEMBERSHIP_PRICE` used anywhere? Was trying to find where it's used so I can work out what format to enter it (ie. `£5` or `5`) but I can't find any uses.

**Review by codemicro — DISMISSED** [review]

**Comment by codemicro** [comment]
@CarrotManMatt - the changes to the configuration that this PR needs are saved in prod and ready to go. That said, this branch has merge commits that I *tried* to resolve but in the process of doing so I broke this branch even more and had to do some Git skullduggery to get it back into its state beforehand.

If you could resolve those conflicts, I'll then be able to re-review and merge.

**Comment by CarrotManMatt** [comment]
> Is `MEMBERSHIP_PRICE` used anywhere? Was trying to find where it's used so I can work out what format to enter it (ie. `£5` or `5`) but I can't find any uses.

Ah yes, thank u for pointing that out. That's one that I added in this branch but meant to remove, because it isn't actually needed (eventually all the Env variables about group specific stuff (except `GROUP_NAME`) should eventually be removed because the messages will be stored in an external `messages.json` file. See [induct.py:117](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/improve-variable-names-and-install-docs-and-.gitignore/cogs/induct.py))

**Review by codemicro — APPROVED** [review]

**Pull request merged**
