### PR TITLE
Use the correct, consistent name for TeX-Bot

### PR DESCRIPTION
**Pull request by CarrotManMatt**

### CODE REVIEW

**Comment by codemicro** [comment]
This PR will break deploys and should not be merged without changing settings on the server

**Comment by CarrotManMatt** [comment]
> This PR will break deploys and should not be merged without changing settings on the server

Agreed

> (though preferably the image tag would not be changed at all as this would also require the deletion of a load of old images to prevent mistypes)

I'm pretty sure we currently are only building the image to the latest tag so all previous image tags have already been deleted? Unless i'm misunderstanding. I'd say TeX-Bot is still not "stable" (currently at v0.5.1 according to semantic versioning this is not "released") so I don't see to big of an issue with changing package names without formal deprecation.

See #164 for my initial ideas on creating the first stable release and tagging releases properly

**Comment by codemicro** [comment]
> I'm pretty sure we currently are only building the image to the latest tag so all previous image tags have already been deleted? 

haha - I wish

Every image that's ever been pushed to a container registry is accessible using its hash - `:latest` is merely a pointer to whatever you most recently pointed it at, kinda like `HEAD` of a Git branch. See them all here: https://github.com/CSSUoB/TeX-Bot-Py-V2/pkgs/container/texbot-py-v2/versions?filters%5Bversion_type%5D=untagged

I use a (deprecated) Actions thing to clean these up in my personal projects since they count towards a storage quota if I remember correctly.

All of that said I'm happy to change the tag name so will approve now and merge at some point in the not so distant future (if I don't forget).

**Review by codemicro — APPROVED** [review]

**Comment by CarrotManMatt** [comment]
> All of that said I'm happy to change the tag name so will approve now and merge at some point in the not so distant future (if I don't forget).

Fab. I'll leave this for you to merge whenever you are ready to fix the deployment. Thank you so much!

**Pull request merged**
